AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - db/**/*
    - .gemspec/**/*
    - .bundle/**/*
    - vendor/**/*
    - config/**/*
    - script/**/*
    - spec/**/*

  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - lib/tasks/**/*.rake
    - lib/tasks/**/*.rb

AlignParameters:
  Enabled: false
ClassLength:
  CountComments: false
  Max: 200
LineLength:
  Max: 99
MethodLength:
  CountComments: false
  Max: 15
Metrics/AbcSize:
  Max: 25
Style/MultilineOperationIndentation:
  EnforcedStyle: indented


inherit_from:
  - .rubocop_todo.yml
